#!/usr/bin/env python3
"""
CampusConnect Environment Setup Script
This script helps set up the development environment for CampusConnect
"""

import os
import secrets
import sqlite3
from pathlib import Path

def create_env_file():
    """Create .env file with default configuration"""
    env_content = """# CampusConnect Environment Configuration
# Generated by setup_environment.py

# Flask Configuration
FLASK_ENV=development
SECRET_KEY={secret_key}

# Database Configuration
DATABASE_URL=sqlite:///database.db

# Email Configuration (for OTP verification)
# Replace with your actual email credentials
MAIL_SERVER=smtp.gmail.com
MAIL_PORT=587
MAIL_USE_TLS=true
MAIL_USERNAME=your-email@gmail.com
MAIL_PASSWORD=your-app-password
MAIL_DEFAULT_SENDER=campusconnect168@gmail.com

# File Upload Configuration
MAX_CONTENT_LENGTH=16777216
UPLOAD_FOLDER=uploads

# Plagiarism Detection
PLAGIARISM_THRESHOLD=0.60
""".format(secret_key=secrets.token_hex(32))
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("✅ Created .env file with default configuration")
    print("⚠️  Please update email credentials in .env file for OTP functionality")

def create_upload_directories():
    """Create necessary upload directories"""
    directories = [
        'uploads',
        'uploads/assignments',
        'uploads/temp'
    ]
    
    for directory in directories:
        Path(directory).mkdir(parents=True, exist_ok=True)
    
    print("✅ Created upload directories")

def initialize_database():
    """Initialize the database if it doesn't exist"""
    if not os.path.exists('database.db'):
        print("📊 Initializing database...")
        os.system('python init_db.py')
        print("✅ Database initialized")
    else:
        print("✅ Database already exists")

def check_dependencies():
    """Check if required Python packages are installed"""
    required_packages = [
        'flask',
        'flask-login',
        'werkzeug',
        'python-docx',
        'PyPDF2',
        'nltk',
        'scikit-learn',
        'numpy',
        'python-dotenv'
    ]
    
    missing_packages = []
    
    for package in required_packages:
        try:
            __import__(package.replace('-', '_'))
        except ImportError:
            missing_packages.append(package)
    
    if missing_packages:
        print("❌ Missing required packages:")
        for package in missing_packages:
            print(f"   - {package}")
        print("\n📦 Install missing packages with:")
        print("   pip install -r requirements.txt")
        return False
    else:
        print("✅ All required packages are installed")
        return True

def main():
    """Main setup function"""
    print("🚀 Setting up CampusConnect development environment...\n")
    
    # Check dependencies
    if not check_dependencies():
        print("\n❌ Setup incomplete. Please install missing dependencies.")
        return
    
    # Create .env file
    create_env_file()
    
    # Create upload directories
    create_upload_directories()
    
    # Initialize database
    initialize_database()
    
    print("\n🎉 Setup complete!")
    print("\n📝 Next steps:")
    print("1. Update email credentials in .env file")
    print("2. Run: python app.py")
    print("3. Open: http://localhost:5000")

if __name__ == "__main__":
    main()
